### ISSUE TITLE
Radio buttons and repeaters don't appear in the spreadsheet

### ISSUE THREAD

**Issue by dpitch** [directus-labs/extensions#30]
### Describe the Bug

Radio buttons and repeaters don't appear in the spreadsheet, I tested every different field, those won't work.

### To Reproduce

Just use a radio button and try to show in the table spreadsheet

### Directus Version

v10.13.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by binaryben** [comment]
Hi, thanks for the report. That is as designed for now. We limited the scope to only handle a subset of field types, mainly those commonly used in a more traditional spreadsheet software. There are no plans currently to increase the scope so I will close this for now.
