### ISSUE TITLE
Anthropic Support  for AI Writer

### ISSUE THREAD

**Issue by treb0r** [directus-labs/extensions#36]
Would you be interested in expanding this extension to include other providers in addition to OpenAI? I was thinking it would be better to build on the excellent work you already have done here. Are you open to pull requests in this regard? 

I'm thinking that although I am particularly interested in accessing the Anthropic models, it might make sense to re-architect the extension to allow multiple providers and models.

**Comment by phazonoverload** [comment]
We'd be very open to this improvement - are you open to doing it?

**Comment by phazonoverload** [comment]
You just took the item for me to tell you it has happened off of my to-do list. Thanks. Heh

**Comment by treb0r** [comment]
Honestly, I was amazed when the lady presenting the changelog video talked about the upgrade and then said it was inspired by an issue on GitHub. I immediately realised that she was talking about me. Directus is such a cool project and you guys rock!
