### ISSUE TITLE
Occasional Internal Error Returned

### ISSUE THREAD

**Issue by binaryben** [directus-labs/extensions#7]
### Extension

AI Alt Text Writer Operation

### Describe the Bug

In flows, occasionally an internal error is returned, especially when nothing has been run through the operation in a while (this seems to be key).

![Occasional Internal Error](https://github.com/directus-labs/extensions/assets/12827556/461fcf04-a00d-4eca-b625-0fb48a0a338c)

This seems like a clarifai/blip issue, but it is of course annoying to have some images return with alt text and others not. I don't personally know a fix, unfortunately, as I am not familiar enough with how clarifai functions or this blip. Maybe the model isn't ready? I see there is a V2 version of blip that may be used, but I assume it wasn't used for a reason.

### To Reproduce

On a postman request to "https://api.clarifai.com/v2/users/salesforce/apps/blip/models/general-english-image-caption-blip/versions/cdb690f13e62470ea6723642044f95e4/outputs" with the same body as the extension uses -

```json
{
  "inputs": [
    {
      "data": {
        "image": {
          "url": "{{directus install url}}/assets/b6aa5e80-bdaf-4f24-b93f-cd386f0a4c41"
        }
      }
    }
  ]
}
```

It returns successfully -

```json
{
  "status": {
    "code": 10000,
    "description": "Ok",
    "req_id": "{{redacted}}"
  },
  "outputs": [
    {
      "id": "{{redacted}}",
      "status": {
        "code": 10000,
        "description": "Ok"
      },
      "created_at": "2024-05-23T00:00:35.406444311Z",
      "model": {
        "id": "general-english-image-caption-blip",
        "name": "Image Captioner",
        "created_at": "2022-04-18T20:01:32.067938Z",
        "modified_at": "2022-08-11T14:01:48.093093Z",
        "app_id": "blip",
        "model_version": {
          "id": "cdb690f13e62470ea6723642044f95e4",
          "created_at": "2023-04-11T21:40:32.444463Z",
          "status": {
            "code": 21100,
            "description": "Model is trained and ready"
          },
          "visibility": {
            "gettable": 50
          },
          "app_id": "blip",
          "user_id": "salesforce",
          "metadata": {}
        },
        "user_id": "salesforce",
        "model_type_id": "image-to-text",
        "visibility": {
          "gettable": 50
        },
        "toolkits": [],
        "use_cases": [],
        "languages": [],
        "languages_full": [],
        "check_consents": [],
        "workflow_recommended": false
      },
      "input": {
        "id": "{{redacted}}",
        "data": {
          "image": {
            "url": "{{redacted}}/assets/b6aa5e80-bdaf-4f24-b93f-cd386f0a4c41"
          }
        }
      },
      "data": {
        "text": {
          "raw": "a photograph of a man and woman taking a selfie with a rainbow - colored rainbow - colored",
          "text_info": {
            "encoding": "UnknownTextEnc"
          }
        }
      }
    }
  ]
}
```

### Directus Version

Unknown

### Hosting Strategy

Directus Cloud

**Comment by binaryben** [comment]
Originally reported by @brrksl prior to migration to monorepo.

**Comment by phazonoverload** [comment]
We'll keep an eye on this, but this does feel to me, unfortunately, like a Clarifai issue.

If that is the case, there's nothing we can do and you should set up the same rejection path handling that any external request should have (same with the Webhook / Request URL operation).

You may choose to run, on a schedule, the same operation on any image without a description, or something else.

I'll leave this open so others can report similar issues if they have them. This is a Labs project, so we don't dedicate much time for maintenance where the path to reproduction isn't clear.
